name: transform-design-tokens
on:
  push:
    branches:
      - "feature/design-tokens"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      # Transform Figma Tokens JSON to something Style Dictionary can read
      - run: npx token-transformer data/figma/tokens.json data/figma/tokens/tokens-transformed.json
      # Convert tokens according to Style Dictionary config
      - run: npx style-dictionary build --config config.json
      # Add files that were created during a run, e.g. created files from style dictionary or token-transformer.
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "feat(design-tokens): transform tokens"
